[book]
authors = ["ysykzheng"]
language = "en"
multilingual = false
src = "src"
title = "Artificial Intelligence and Smart Cities: The Role of Intelligent Technologies in Building Sustainable and Livable Cities"
